[package]
name = "trees"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.46.0", features = ["csv", "lazy", "mode"] }
polars-core = "0.46.0"
polars-lazy = "0.46.0"
thiserror = "2.0.12"
#polars = { version = "0.46.0", features = ["csv", "lazy"] }

